[package]
name = "roux"
version = "0.0.1"
edition = "2021"
description = "Lightwieght AOI"
authors = [
  "bradmartin333"
]

[lib]
name="roux"
crate-type = ["dylib"]

[features]

[dependencies]
glium = "0.31.0"
